apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  namespace: demo-namespace
data:
  redis_host: "redis-0.redis.demo-namespace.svc.cluster.local"
  redis_port: "6379"
  log_level: "info"