apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  volumes:
    - name: shared-data
      persistentVolumeClaim:
        claimName: efs-pvc
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: shared-data
          mountPath: /data