apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: demo-namespace
spec:
  type: ClusterIP              # Internal only (Ingress will expose it)
  selector:
    app: api                   # Find pods with label app=api
  ports:
    - port: 80                 # Service port (what others call)
      targetPort: 8080         # Pod port (where app listens)